version: "3"
services:
  research-eureka-server:
    build: .   # 使用 Dockerfile 构建镜像
    # command: ["--spring.profiles.active=${ACTIVE_PROFILE:-docker}"]
    # image: java
    container_name: research-eureka-server-compose
    environment:
      TZ: 'Asia/Shanghai'
    ports:
      - "8761:8761"
    expose:
      - 8761
    # build: ./target

#
# 启动
# docker-compose --compatibility up -d

# 查看容器日志最后10行
# docker logs -f -t --tail 1000 research-eureka-server-compose

# 进入容器
# docker exec -it research-eureka-server-compose /bin/bash
# 停止
# docker-compose stop
